#:kivy 1.0


<Controller>:
    # text_input1: text_input1
    # text_input2: text_input2
    # label_results: label_results
    # label_debug: label_debug
    # toggle_debug: toggle_debug
    # toggle_variante: toggle_variante


    canvas:
        Rectangle:
            source: '../DHBW-Raute-Big.png'
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'horizontal'

		Button:
			id: btn1
			size_hint: (.3, .3)
			background_color: [1, 0, 0, 1]
			text: 'Hello'

		Button:
			id: btn1 
			size_hint: (.3, .3)
			background_color: [.7, .7, .7, 1]
			text: 'World'

		Label:
			size_hint: (.3, .3)
